service: logging

provider:
  name: aws
  runtime: nodejs14.x
  stage: dev
  region: us-west-3
  role: arn:aws:iam::729503035905:role/myapp-logging-role

functions:
  dispatchErrors:
    handler: handler.dispatchErrors
    events:
      - sns: arn:aws:sns:us-east-1:729503035905:PRODUCTION_ERRORS
