service: send-error-report

custom:
  SNS:
    topic: ${self:service}-sns-topic
  SES: 
    arn: arn:aws:ses:${aws:region}:${aws:accountId}:identity/${self.environment.AWS_EMAIL}
  LOGS: 
    arn: arn:aws:logs:${aws:region}:${aws:accountId}:log-group:*

provider:
  name: aws
  runtime: nodejs14.x
  stage: ${opt:stage, 'dev'}
  region: eu-west-3
  lambdaHashingVersion: 20201221

  environment:
    AWS_EMAIL: antonio.pierro@gmail.com
    AWS_SES_ARN: arn:aws:ses:${aws:region}:${aws:accountId}:identity/antonio.pierro@gmail.com
  
  iamRoleStatements:
    - Effect: Allow
      Action: 
        - logs:DescribeMetricFilters
        - logs:FilterLogEvents
      Resource: ${self:custom.LOGS.arn}
    - Effect: Allow
      Action: "*"
      Resource: "*"

functions:
  dispatcherErrors:
    handler: lambdas/dispatch-error.handler
    events:
      - sns:
          topicName: ${self:custom.SNS.topic}
