service: logging

custom:
  SNS:
    topic: logging-sns-topic-2
  SES: 
    arn: arn:aws:ses:${aws:region}:${aws:accountId}:identity/${self.environment.AWS_EMAIL}
  LOGS: 
    arn: arn:aws:logs:${aws:region}:${aws:accountId}:log-group:*

provider:
  name: aws
  runtime: nodejs14.x
  stage: dev
  region: eu-west-3
  lambdaHashingVersion: 20201221

  environment:
    AWS_EMAIL: antonio.pierro@gmail.com
    AWS_SES_ARN: arn:aws:ses:${aws:region}:${aws:accountId}:identity/${self.environment.AWS_EMAIL}
  
  iamRoleStatements:
    - Effect: Allow
      Action: 
        - logs:DescribeMetricFilters
        - logs:FilterLogEvents
      Resource: ${self:custom.LOGS.arn}
    - Effect: Allow
      Action: ses:SendEmail
      Resource: ${self:custom.SES.arn}

functions:
  dispatcherErrors:
    handler: handler.dispatchErrors
    events:
      - sns: ${self:custom.SNS.topic}
