service: notes

provider:
  lambdaHashingVersion: 20201221
  name: aws
  region: eu-west-3
  runtime: nodejs14.x
  stage: dev
  environment:
    APP_NAME: My Notes App
    APP_STAGE: ${opt:stage,self:provider.stage}
    SERVICE_NAME: Notes Service

functions:
  createNotes:
    handler: handler.createNotes
    timeout: 1
    memorySize: 128
    events:
      - http:
          path: notes
          method: post

  getNoteById:
    handler: handler.getNotesById
    timeout: 1
    memorySize: 128
    events:
      - http:
          path: notes/{id}
          method: get          
